/* 회원관리 */
CREATE TABLE MEMBERT (
	MEM_NUM NUMBER(6) NOT NULL, /* 회원번호 */
	MEM_REGION VARCHAR2(40), /* 지역(기본 지역) */
	AGE NUMBER(3), /* 나이 */
	EMAIL VARCHAR2(100) NOT NULL, /* 이메일(아이디) */
	NICKNAME VARCHAR2(15) NOT NULL, /* 닉네임 */
	PWD VARCHAR2(30), /* 비밀번호 */
	GENDER VARCHAR2(3), /* 성별 */
	TENDENCY VARCHAR2(30) /* 체질 */
);

CREATE UNIQUE INDEX PK_MEMBERT
	ON MEMBERT (
		MEM_NUM ASC
	);

CREATE UNIQUE INDEX UIX_MEMBERT
	ON MEMBERT (
		EMAIL ASC,
		NICKNAME ASC
	);

ALTER TABLE MEMBERT
	ADD
		CONSTRAINT PK_MEMBERT
		PRIMARY KEY (
			MEM_NUM
		);

ALTER TABLE MEMBERT
	ADD
		CONSTRAINT UK_MEMBERT
		UNIQUE (
			EMAIL,
			NICKNAME
		);

// 회원번호 시퀀스, 시군구 순번 시퀀스
create sequence MEMBERT_SEQ start with 0 INCREMENT BY 1  MINVALUE 0 nocache nocycle;
create sequence REGION_LALO_SEQ start with 0 INCREMENT BY 1  MINVALUE 0 nocache nocycle;
create sequence COMMENT_NUM_SEQ start with 0 INCREMENT BY 1 MINVALUE 0 nocache nocycle;

/* 코디정보 */
CREATE TABLE CLOTHING_MATCH (
	DEGREEC NUMBER(3), /* 기온 */
	WIND NUMBER(3), /* 풍속 */
	TRAIT VARCHAR2(30), /* 특성 */
	TDATE DATE, /* 날짜 */
	REG_NAME VARCHAR2(30), /* 시군구명 */
	MEM_NUM NUMBER(6), /* 회원번호 */
	TOP VARCHAR2(30), /* 옷(상의) */
	BOTTOM VARCHAR2(30), /* 옷(하의) */
	TOUTER VARCHAR2(30), /* 옷(겉옷) */
	ETC VARCHAR2(30), /* 옷(기타) */
	FEELING VARCHAR2(30), /* 느낌 */
	PHOTONAME VARCHAR2(100) /* 사진이름 */
);

/* 옷 */
CREATE TABLE CLOTHING (
	CAT VARCHAR2(30), /* 분류 */
	CNAME VARCHAR2(30) /* 이름 */
);

/* 지역 */
CREATE TABLE REGION (
	DEGREEC NUMBER(3), /* 기온 */
	WIND NUMBER(3), /* 풍속 */
	TRAIT VARCHAR2(30), /* 특성 */
	REG_NAME VARCHAR2(30), /* 시군구명 */
	TDATE DATE, /* 날짜 */
	AM_PM VARCHAR2(10) /* 오전/오후 */
);

/* 게시판 */
CREATE TABLE CHATBOARD (
    COMMENT_NUM NUMBER(5),
	TDATE DATE, /* 날짜 */
	REGION VARCHAR2(40), /* 지역 */
	COMMENTC VARCHAR2(100), /* 한줄평 */
	MEM_NUM NUMBER(6) /* 회원번호 */
);
ALTER TABLE CHATBOARD
	ADD
		CONSTRAINT PK_CHATBOARD
		PRIMARY KEY (
			COMMENT_NUM
		);

/* 체질 */
CREATE TABLE TENDENCY_TABLE (
	TENDENCY VARCHAR2(30) /* 체질 */
);

/* 평가 */
CREATE TABLE FEELING_TABLE (
	CONTENT VARCHAR2(30) /* 내용 */
);

/* 위도경도 */
CREATE TABLE REGION_LALO (
	REG_NAME VARCHAR2(30) NOT NULL, /* 시군구명 */
	REG_NUM NUMBER(15), /* 순번 */
	REG_CODE NUMBER(30), /* 시군구코드 */
	REG_ENAME VARCHAR2(30), /* 시군구명영어 */
	LONGITUDE NUMBER NOT NULL, /* 경도 */
	LATITUDE NUMBER NOT NULL /* 위도 */
);

CREATE UNIQUE INDEX PK_REGION_LALO
	ON REGION_LALO (
		REG_NAME ASC
	);

ALTER TABLE REGION_LALO
	ADD
		CONSTRAINT PK_REGION_LALO
		PRIMARY KEY (
			REG_NAME
		);

ALTER TABLE CLOTHING_MATCH
	ADD
		CONSTRAINT FK_MEMBERT_TO_CLOTHING_MATCH
		FOREIGN KEY (
			MEM_NUM
		)
		REFERENCES MEMBERT (
			MEM_NUM
		);

ALTER TABLE REGION
	ADD
		CONSTRAINT FK_REGION_LALO_TO_REGION
		FOREIGN KEY (
			REG_NAME
		)
		REFERENCES REGION_LALO (
			REG_NAME
		);

ALTER TABLE CHATBOARD
	ADD
		CONSTRAINT FK_MEMBERT_TO_CHATBOARD
		FOREIGN KEY (
			MEM_NUM
		)
		REFERENCES MEMBERT (
			MEM_NUM
		);

select * from tab;
