/* 회원관리 */
DROP TABLE MEMBERT 
	CASCADE CONSTRAINTS;

/* 코디정보 */
DROP TABLE CLOTHING_MATCH 
	CASCADE CONSTRAINTS;

/* 옷 */
DROP TABLE CLOTHING 
	CASCADE CONSTRAINTS;

/* 지역 */
DROP TABLE REGION 
	CASCADE CONSTRAINTS;

/* 게시판 */
DROP TABLE CHATBOARD 
	CASCADE CONSTRAINTS;

/* 체질 */
DROP TABLE TENDENCY_TABLE 
	CASCADE CONSTRAINTS;

/* 평가 */
DROP TABLE FEELING_TABLE 
	CASCADE CONSTRAINTS;

/* 위도경도 */
DROP TABLE REGION_LALO 
	CASCADE CONSTRAINTS;

/* 시퀀스 삭제 */
DROP SEQUENCE MEMBERT_SEQ;
DROP SEQUENCE REGION_LALO_SEQ;
DROP SEQUENCE COMMENT_NUM_SEQ;
// 휴지통 정리
purge recyclebin;

/* 시퀀스 확인 */
select * from seq;
