/* 삭제 구문 */  #참고 TRUNCATE TABLE 테이블명 ---- 데이터만 삭제 됨 

DROP TABLE MUTE;
DROP TABLE AUTHORITY;
DROP TABLE LIKES;
DROP TABLE BLOCK;

DROP TABLE FOLLOWING;
DROP TABLE FOLLOWER;
DROP TABLE NOTE_FILE;
DROP TABLE MENTION;
DROP TABLE FOLLOWING;
DROP TABLE NOTE;
DROP TABLE BOARD_FILE;
DROP TABLE BOARD;
DROP TABLE MEMBER;
DROP TABLE FILES;

COMMIT;

/* 파일 */
CREATE TABLE FILES (
   F_NO INT(15) PRIMARY KEY AUTO_INCREMENT, /* 파일번호 */
   F_NAME VARCHAR(100) NOT NULL, /* 파일이름 */
   F_SAVENAME VARCHAR(130) NOT NULL, /* 저장이름 */
   F_TYPE VARCHAR(10) NOT NULL, /* 파일형식 */
   F_SIZE INT(8) NOT NULL /* 파일크기 */
);
CREATE UNIQUE INDEX PK_FILES ON FILES (F_NO ASC);
CREATE UNIQUE INDEX UIX_FILES ON FILES (F_SAVENAME ASC);

/* 회원 */
CREATE TABLE MEMBER (
   M_NO INT(11) AUTO_INCREMENT PRIMARY KEY, /* 회원번호 */
   M_ID VARCHAR(30) NOT NULL, /* 아이디 */
   M_NAME VARCHAR(15) NOT NULL, /* 이름 */
   M_EMAIL VARCHAR(30), /* 이메일 */
   M_PHONE VARCHAR(11), /* 전화번호 */
   M_PASSWORD VARCHAR(15) NOT NULL, /* 비밀번호 */
   M_PROFILE INT(15), /* 프로필사진 */
   M_HEADER INT(15), /* 헤더사진 */
   M_DELETE INT(2), /* 자동삭제기간 */
   M_RDATE date NOT NULL, /* 가입일 */ 
   
   FOREIGN KEY (M_PROFILE) REFERENCES FILES(F_NO) ON DELETE CASCADE,
   FOREIGN KEY (M_HEADER) REFERENCES FILES(F_NO) ON DELETE CASCADE
);
CREATE UNIQUE INDEX PK_MEMBER ON MEMBER (M_NO ASC);
CREATE UNIQUE INDEX UIX_MEMBER ON MEMBER (M_ID ASC);
CREATE UNIQUE INDEX UIX_MEMBER2 ON MEMBER (M_EMAIL ASC);
CREATE UNIQUE INDEX UIX_MEMBER3 ON MEMBER (M_PHONE ASC);  

/* 게시물 */
CREATE TABLE BOARD (
   B_NO INT(15) PRIMARY KEY AUTO_INCREMENT, /* 게시물번호 */
   M_NO INT(11) NOT NULL, /* 회원번호 */
   B_CONTENT VARCHAR(420) NOT NULL, /* 내용 */
   B_REBUZ INT(11) NOT NULL, /* 리버징수 */
   B_LIKE INT(15) NOT NULL, /* 하트수 */
   B_REF INT(15) NOT NULL, /* 레퍼런스 */
   B_RDATE DATE NOT NULL, /* 작성일 */
   FOREIGN KEY (M_NO) REFERENCES MEMBER(M_NO) ON DELETE CASCADE,
   FOREIGN KEY (B_REF) REFERENCES BOARD(B_NO) ON DELETE CASCADE
);
CREATE UNIQUE INDEX PK_BOARD ON BOARD (B_NO ASC);

/* 게시파일 */
CREATE TABLE BOARD_FILE (
   B_NO INT(15) NOT NULL, /* 게시물번호 */
   F_NO INT(15) NOT NULL, /* 파일번호 */
    
    FOREIGN KEY (B_NO) REFERENCES BOARD(B_NO) ON DELETE CASCADE,
    FOREIGN KEY (F_NO) REFERENCES FILES(F_NO) ON DELETE CASCADE
);
CREATE UNIQUE INDEX PK_BOARD_FILE ON BOARD_FILE (B_NO ASC,F_NO ASC); 
ALTER TABLE BOARD_FILE ADD CONSTRAINT PK_BOARD_FILE PRIMARY KEY (B_NO,F_NO);

/* 팔로잉 */
CREATE TABLE FOLLOWING (
   M_NO INT(11) NOT NULL, /* 회원번호 */
   M_NO2 INT(11) NOT NULL, /* 팔로잉번호 */
   MUTE VARCHAR(1), /* 뮤트 */
    
    FOREIGN KEY (M_NO) REFERENCES MEMBER(M_NO) ON DELETE CASCADE,
    FOREIGN KEY (M_NO2) REFERENCES MEMBER(M_NO) ON DELETE CASCADE
);
CREATE UNIQUE INDEX PK_FOLLOWING ON FOLLOWING (M_NO ASC,M_NO2 ASC);
ALTER TABLE FOLLOWING ADD CONSTRAINT PK_FOLLOWING PRIMARY KEY (M_NO,M_NO2);


/* 블락 */
CREATE TABLE BLOCK (
   M_NO INT(11) NOT NULL, /* 회원번호 */
   M_NO2 INT(11) NOT NULL, /* 블락한회원 */
    
   FOREIGN KEY (M_NO) REFERENCES MEMBER(M_NO) ON DELETE CASCADE,
   FOREIGN KEY (M_NO2) REFERENCES MEMBER(M_NO) ON DELETE CASCADE
);
CREATE UNIQUE INDEX PK_BLOCK ON BLOCK (M_NO ASC,M_NO2 ASC);
ALTER TABLE BLOCK ADD CONSTRAINT PK_BLOCK PRIMARY KEY (M_NO,M_NO2);

/* 쪽지 */
CREATE TABLE NOTE (
   N_NO INT(15) PRIMARY KEY AUTO_INCREMENT, /* 쪽지번호 */
   M_NO INT(11) NOT NULL, /* 회원번호 */
   M_NO2 INT(11) NOT NULL, /* 상대번호 */
   N_CONTENT VARCHAR(1000) NOT NULL, /* 내용 */
   N_RDATE DATE NOT NULL, /* 작성일 */
    
    FOREIGN KEY (M_NO) REFERENCES MEMBER(M_NO),
    FOREIGN KEY (M_NO2) REFERENCES MEMBER(M_NO)
);
CREATE UNIQUE INDEX PK_NOTE ON NOTE (N_NO ASC);

/* 쪽지파일 */
CREATE TABLE NOTE_FILE (
   N_NO INT(15) NOT NULL, /* 쪽지번호 */
   F_NO INT(15) NOT NULL, /* 파일번호 */
    
    FOREIGN KEY (N_NO) REFERENCES NOTE(N_NO) ON DELETE CASCADE,
    FOREIGN KEY (F_NO) REFERENCES FILES(F_NO) ON DELETE CASCADE
);
CREATE UNIQUE INDEX PK_NOTE_FILE ON NOTE_FILE (N_NO ASC,F_NO ASC);
ALTER TABLE NOTE_FILE ADD CONSTRAINT PK_NOTE_FILE PRIMARY KEY (N_NO,F_NO);

/* 권한 */
CREATE TABLE AUTHORITY (
   M_NO INT(11) NOT NULL, /* 회원번호 */
   A_ENABLED CHAR(1) NOT NULL, /* 활성화 */
   A_AUTH VARCHAR(15) NOT NULL, /* 권한 */
    
    FOREIGN KEY (M_NO) REFERENCES MEMBER(M_NO) ON DELETE CASCADE
);
CREATE UNIQUE INDEX PK_AUTHORITY ON AUTHORITY (M_NO ASC);
ALTER TABLE AUTHORITY ADD CONSTRAINT PK_AUTHORITY PRIMARY KEY (M_NO);

/* 관심글 */
CREATE TABLE LIKES (
   M_NO INT(11) NOT NULL, /* 회원번호 */
   B_NO INT(15) NOT NULL, /* 게시물번호 */
   FOREIGN KEY (M_NO) REFERENCES MEMBER(M_NO) ON DELETE CASCADE,
    FOREIGN KEY (B_NO) REFERENCES BOARD(B_NO) ON DELETE CASCADE
);
CREATE UNIQUE INDEX PK_LIKES ON LIKES (M_NO ASC,B_NO ASC);
ALTER TABLE LIKES ADD CONSTRAINT PK_LIKES PRIMARY KEY (M_NO,B_NO);

/* 뮤트한글 */
CREATE TABLE MUTE (
   M_NO INT(11) NOT NULL, /* 회원번호 */
   B_NO INT(15) NOT NULL, /* 게시물번호 */
    
    FOREIGN KEY (M_NO) REFERENCES MEMBER(M_NO) ON DELETE CASCADE,
    FOREIGN KEY (B_NO) REFERENCES BOARD(B_NO) ON DELETE CASCADE
);
CREATE UNIQUE INDEX PK_MUTE ON MUTE (M_NO ASC,B_NO ASC);
ALTER TABLE MUTE ADD CONSTRAINT PK_MUTE PRIMARY KEY (M_NO,B_NO);

/* 팔로워 */
CREATE TABLE FOLLOWER (
   M_NO INT(11) NOT NULL, /* 회원번호 */
   M_NO2 INT(11) NOT NULL, /* 팔로워번호 */
    
    FOREIGN KEY (M_NO) REFERENCES MEMBER(M_NO) ON DELETE CASCADE,
    FOREIGN KEY (M_NO2) REFERENCES MEMBER(M_NO) ON DELETE CASCADE
);
CREATE UNIQUE INDEX PK_FOLLOWER ON FOLLOWER (M_NO ASC,M_NO2 ASC);
ALTER TABLE FOLLOWER ADD CONSTRAINT PK_FOLLOWER PRIMARY KEY (M_NO,M_NO2);

/* 멘션 */
CREATE TABLE MENTION (
   B_NO INT(15) NOT NULL, /* 게시물번호 */
   M_NO INT(11) NOT NULL, /* 회원번호 */
    
    FOREIGN KEY (B_NO) REFERENCES BOARD(B_NO) ON DELETE CASCADE,
    FOREIGN KEY (M_NO) REFERENCES MEMBER(M_NO) ON DELETE CASCADE
);
CREATE UNIQUE INDEX PK_MENTION ON MENTION (B_NO ASC,M_NO ASC);
ALTER TABLE MENTION ADD CONSTRAINT PK_MENTION PRIMARY KEY (B_NO,M_NO);


insert into FILES (F_NAME, F_SAVENAME, F_TYPE, F_SIZE) values('mb.png', 'mp.png', 'mp.png', 1);
insert into FILES (F_NAME, F_SAVENAME, F_TYPE, F_SIZE) values('b', 'b', 'b', 1);
insert into FILES (F_NAME, F_SAVENAME, F_TYPE, F_SIZE) values('c', 'c', 'c', 1);
insert into FILES (F_NAME, F_SAVENAME, F_TYPE, F_SIZE) values('d', 'd', 'd', 1);

insert into MEMBER (M_ID, M_NAME, M_EMAIL, M_PHONE, M_PASSWORD, M_PROFILE, M_HEADER, M_DELETE, M_RDATE) values('admin', '홍길동', 'aa@aa.aa', '01012344321', '{noop}admin', 1, 1, null, now());
insert into MEMBER (M_ID, M_NAME, M_EMAIL, M_PHONE, M_PASSWORD, M_PROFILE, M_HEADER, M_DELETE, M_RDATE) values('user1', '홍길서', 'bb@aa.aa', '01012344322', '{noop}1234', 2, 2, null, NOW());
insert into MEMBER (M_ID, M_NAME, M_EMAIL, M_PHONE, M_PASSWORD, M_PROFILE, M_HEADER, M_DELETE, M_RDATE) values('user2', '홍길남', 'cc@aa.aa', '01012344323', '{noop}1234', 3, 3, null, NOW());
insert into MEMBER (M_ID, M_NAME, M_EMAIL, M_PHONE, M_PASSWORD, M_PROFILE, M_HEADER, M_DELETE, M_RDATE) values('user3', '홍길북', 'dd@aa.aa', '01012344324', '{noop}1234', 4, 4, null, NOW());

insert into AUTHORITY (M_NO, A_ENABLED, A_AUTH) values(1, 1, 'ROLE_ADMIN');
insert into AUTHORITY (M_NO, A_ENABLED, A_AUTH) values(2, 1, 'ROLE_USER');
insert into AUTHORITY (M_NO, A_ENABLED, A_AUTH) values(3, 1, 'ROLE_USER');
insert into AUTHORITY (M_NO, A_ENABLED, A_AUTH) values(4, 1, 'ROLE_USER');

insert into FOLLOWER (M_NO, M_NO2) values(1, 2);
insert into FOLLOWING (M_NO, M_NO2, MUTE) values(2, 1, 'N');
insert into FOLLOWING (M_NO, M_NO2, MUTE) values(1, 3, 'N');
insert into FOLLOWER (M_NO, M_NO2) values(3, 1);

commit;
